### ISSUE TITLE
Found missing curl_close() in the providers

### ISSUE THREAD

**Issue by ednt** [espocrm/ext-sms-providers#8]
During adding playSMS

https://playsms.org/

to this repository I saw that close_curl() is never used to free the curl resources.
Maybe this results in a memory problem. I'm not a php specialist, maybe it is freed by php.
But at least it is not good practise. Also the result of cur_init() should be checked.

Best regards.

**Comment by yurikuzn** [comment]
There's no need. See https://www.php.net/manual/en/function.curl-close.php

**Comment by ednt** [comment]
> Prior to PHP 8.0.0, this function was used to close the resource

Who uses already 8.0.0?
We use PHP 7.4.

**Comment by yurikuzn** [comment]
Sorry, I'm extremely busy. Can't explain. We don't need curl close.
